### PR TITLE
Tools 389

### PR DESCRIPTION
**Pull request by NTCoding**

### CODE REVIEW

**Comment by urtens** [comment]
@Bellspringsteen EC2 instances are using instance profiles so no aws api keys required

**Comment by urtens** [comment]
@jonauman The confusion with the title is my fault; they are both subtasks of TOOLS-382 and I created the original encrypted credentials branch with the incorrect number.

**Comment by NTCoding** [comment]
@jonauman This is TOOLS-389.

**Comment by NTCoding** [comment]
@Bellspringsteen I've made some updates to the readme, thanks.

There are a few things slightly different to your suggestions:

- We have decided to use Python 3.6 here  https://github.com/LinkNYC/tablet-credentials-provider/pull/4/files#diff-88f8692ab33ad33d5baa1c2679239fdbR10 but you don't really need this installed because we install for you inside the dev environment https://github.com/LinkNYC/tablet-credentials-provider/pull/4/files#diff-3254677a7917c6c01f55212f86c57fbfR1.

This is our first lambda, though, and we're just in the process of feeling our way forward, so these conventions and principles are open for discussion. There are no decision here that we can't change.

**Comment by NTCoding** [comment]
@Bellspringsteen btw, we are using path lib in the unit tests https://github.com/LinkNYC/tablet-credentials-provider/blob/master/src/test/lambda/basic_lambda_test.py#L10

**Comment by Bellspringsteen** [comment]
@NTCoding your responses make sense. For pathlib, should it be in the requirements.txt?

**Comment by NTCoding** [comment]
@Bellspringsteen I'm fixing the tests that use pathlib on the next ticket, currently they are disabled due to docker. Will resolve on that ticket (TOOLS-390). Thanks

**Pull request merged**
